# Generated by Django 4.2.2 on 2023-06-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonatos',
            fields=[
                ('id_campeonato', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id_carteira', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id_odds', models.AutoField(primary_key=True, serialize=False)),
                ('odd_casa', models.FloatField()),
                ('odd_empate', models.FloatField()),
                ('odd_fora', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoAposta',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('cpf', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('email', models.TextField()),
                ('data_nascimento', models.DateField()),
                ('id_carteira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_unibet.carteira')),
            ],
        ),
        migrations.CreateModel(
            name='Partidas',
            fields=[
                ('id_partida', models.AutoField(primary_key=True, serialize=False)),
                ('time_casa', models.IntegerField()),
                ('time_fora', models.IntegerField()),
                ('horario', models.DateTimeField()),
                ('id_campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_unibet.campeonatos')),
                ('id_odds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_unibet.odds')),
            ],
        ),
        migrations.CreateModel(
            name='Apostas',
            fields=[
                ('id_aposta', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('retorno', models.FloatField()),
                ('resultado', models.IntegerField()),
                ('finalizada', models.IntegerField()),
                ('id_partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_unibet.partidas')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_unibet.tipoaposta')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_unibet.usuarios')),
            ],
        ),
    ]
