# Generated by Django 4.2.2 on 2023-06-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_unibet', '0003_alter_apostas_finalizada_alter_apostas_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apostas',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_unibet.usuarios'),
        ),
    ]
